### ISSUE TITLE
Parse lm_sensors config file/output to obtain labels and math

### ISSUE THREAD

**Issue by oliv3r** [corecoding/Vitals#423] opened 2024-04-10 13:46 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

I have lm_sensors installed as per README. Running sensors shows me my (it8721 based) sensor data, with math correction and labels as set per configuration file.

Howver Vitals will use the sysfs names, without doing any of the math on values. This leaves me with universal labels (as per sysfs) and incorrect voltages.

**Comment by corecoding** [comment] 2024-05-04 21:21
I think it is time this feature started moving forward. This is actually a duplicate of #83 and #68. Please vote in the respective tickets. I'm going to tag them so they stay prominent.

**Closed by corecoding** 2024-05-04 21:21 UTC
Labels: feature
