### ISSUE TITLE
Assign meaningful names for sensors?

### ISSUE THREAD

**Issue by tdgvrr** [corecoding/Vitals#353] opened 2023-05-25 22:40 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Perhaps there's already a way to do this, but I'm seeing meaningless names for the sensors in the display. Instead of "fan 1", "fan 2" etc, I'd like to see "radiator fan", "chassis fan", "CPU fan" and so on. Same for the voltages and temperature probes (though those are a bit better by default).

**Comment by corecoding** [comment] 2023-05-27 03:32
This is a duplicate of #83. I can't foresee creating a UI for custom labels, but /etc/sensors3.conf will be used. Please voice your support in #83. Thank you!

**Closed by corecoding** 2023-05-27 03:32 UTC
Labels: feature
