### ISSUE TITLE
Fixed widths (No jumping)

### ISSUE THREAD

**Issue by ccrisan** [corecoding/Vitals#55] opened 2018-12-02 17:34 UTC
How can I make the widget have a fixed width, either entirely or for each information displayed? When displaying the network upload/download, values change often and move the widgets on the top bar, creating an unwanted visual effect.

**Comment by wolfen351** [comment] 2019-11-01 00:26
A suggestion - Use unicode special space characters to pad the width to a specific size

**Comment by Tharwat96** [comment] 2019-11-30 23:15
fixing this will be great if possible or if there is a way to manually do it.

**Comment by Obihoernchen** [comment] 2020-05-20 00:35
The last feature missing to make this the perfect system monitor tool!

**Comment by corecoding** [comment] 2020-05-22 13:36
I have started looking into this feature. Setting width is easy. Harder part is figuring out the proper max width for each item. Even items in the same section have different widths, like the IP Address one.

**Comment by Obihoernchen** [comment] 2020-05-22 14:44
Maybe adding an user input for each column, so users can set a specific width based on their configuration?

**Comment by wolfen351** [comment] 2020-05-24 01:03
Thanks for looking into this one! :)

**Comment by coffeemug** [comment] 2020-05-26 12:08
> I have started looking into this feature. Setting width is easy. Harder part is figuring out the proper max width for each item. Even items in the same section have different widths, like the IP Address one.

I'd just keep the width from shrinking. This way it might occasionally increase, but that's ok. So long as it doesn't jump around back and forth every few seconds, it isn't really a problem.

**Comment by corecoding** [comment] 2020-05-26 13:13
Yes, that was my idea too. However, I can’t find anything out of the box in the St.Label that does this. This means I have to calculate widths manually and keep track of them. That’s not the end of the world, until you add support for different fonts and font sizes. 

Even if I grab the current width and stick it in an array, and check if the new width is smaller than the previous width, it would still cause jumping effect. 

If anyone has any ideas in how to do this (code wise) it would be appreciated.

**Comment by wolfen351** [comment] 2020-05-28 10:39
Just let me enter a hardcoded number input box for the size, I'll choose something that works for my situation.

**Comment by wolfen351** [comment] 2020-05-28 11:33
Or where you have the calculation you are planning on doing, just do it for a "standard" font, and let me manually enter a "scaling factor" to even out any weirdness caused by fonts etc

**Comment by coffeemug** [comment] 2020-05-29 09:10
Yup, that would work for me too. Strongly agree.

**Comment by blipk** [comment] 2020-05-29 10:33
A possible way to determine the width is to loop through each of the label texts, counting the characters then using set_style to set the width in em/ch based on the amount of characters, would also need to add widths for the amount of icons (possibly probing icon_size for each) + an amount of nominal padding to prevent constant small fluctuations.

**Comment by mkoreneff** [comment] 2020-05-30 21:07
Is it possible to set the width using css in StWidget.st_widget_set_style()?

**Comment by corecoding** [comment] 2020-06-06 18:20
I pushed some changes in, which I think are closer to what you are expecting. Let me know what you think. It is on the develop branch.

**Comment by wolfen351** [comment] 2020-06-07 00:54
I had a quick look at the implementation, looking good! I see you went for the 'don't decrease' approach, which is the best one imo

**Comment by corecoding** [comment] 2020-06-07 02:11
I think so too. Unfortunately, I had to create a private var to keep track of the widths. I tried using the current width of the label, but it wasn’t working correctly.

**Comment by corecoding** [comment] 2020-07-04 14:53
Can anyone else verify that this is working for them?

**Comment by Obihoernchen** [comment] 2020-07-09 21:24
Just tested it and Network is fixed width now, but Processor is not. Width differs between single and double digit and thus moves all other figures.

**Comment by Obihoernchen** [comment] 2020-07-20 08:46
Furthermore, if I get figures like `743 KB/s` network speed the `s` is not showing. Looks like the fixed width is slightly too small

**Comment by wolfen351** [comment] 2020-08-24 04:22
I've been using this for a few weeks now, and it's brilliant, working great! Thanks

**Comment by glebr** [comment] 2021-01-30 16:59
Just let the user set the width manually. This is implemented in resource_monitor gnome-shell extension: https://github.com/0ry0n/Resource_Monitor/

**Comment by kohane27** [comment] 2021-10-15 21:09
I'm reporting that with `use fixed widths (beta)` enabled, for the Processor tab, the digit still moves and changes width.

**Comment by corecoding** [comment] 2022-02-24 05:51
The issue was that when you toggle an option in preferences, or login/logout, fixed widths stopped working. This is fixed in the latest release, which should come out tomorrow. If you experience other issues, please feel free to open a new ticket.

**Closed by corecoding** 2022-02-24 05:51 UTC
Labels: bug

**Comment by ilavidas** [comment] 2022-03-06 15:52
Fixed width seems to be working, thank you!

**Comment by HubKing** [comment] 2023-09-21 08:40
It seems that fixed width setting is not applied to items that is after turning the setting on. I had to disable and re-enable it to apply fixed width to new items. Please check if this is a bug.
