### ISSUE TITLE
Network - total downloaded/uploaded

### ISSUE THREAD

**Issue by den7007** [corecoding/Vitals#234] opened 2022-02-13 15:24 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

#229 

Wondering if possible to include total amount downloaded/uploaded for the session as another item under Network? And maybe an option to reset the counter whenever we choose?

**Comment by corecoding** [comment] 2022-02-19 14:37
Sorry, I know I asked you to create this second request, but I realized it is a duplicate of #216. Good news is that's the feature I'm working on today!

**Comment by den7007** [comment] 2022-02-21 10:45
> Sorry, I know I asked you to create this second request, but I realized it is a duplicate of #216. Good news is that's the feature I'm working on today!

Hi, was looking for total amount downloaded/uploaded for the session, not total download/upload speed, if that makes sense.

Something similar to what is implemented here (5th mode): https://extensions.gnome.org/extension/3724/net-speed-simplified/

**Comment by corecoding** [comment] 2022-03-09 03:34
This has been added to the latest master branch. It should be released within a week.

**Closed by corecoding** 2022-03-09 03:34 UTC
Labels: feature
