### ISSUE TITLE
Alerts for temperature and battery

### ISSUE THREAD

**Issue by T3sT3ro** [corecoding/Vitals#308] opened 2023-01-09 17:28 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

Would it be possible to add a support for alerts/notifications when certain sensor thresholds are crossed?

It would be useful for me to monitor the temperature and show an alert if certain threshold is crossed, as well as setup multiple checkpoints when running out of battery. I haven't found any satisfactory native ways of monitoring those things. UPower, for example, can't configure more than 2 levels for battery power — low and critical. Also I found no nice solution for monitoring temperature and alerting me when something is not OK.

This would be very helpful for me, because my hardware fans fail very rarely, and the PC can overheat and without any warning shutdown immediately. Same goes for the battery, which can discharge randomly in a span of a few minutes, and I sometimes dismiss warnings until the battery is critically low. 

For battery it would be nice to have "alert when threshold crossed" and "alert every X units after threshold crossed", for example every 3% if below 15%.

**Comment by corecoding** [comment] 2023-01-10 03:19
Thank you for this idea! This is a duplicate of #68. Can you add your comments over there? I believe you have some additional thoughts that could be considered.

**Closed** 2023-01-10 03:21 UTC
Labels: feature
