### ISSUE TITLE
GNOME 3.34 Update

### ISSUE THREAD

**Issue by mon0theist** [corecoding/Vitals#105] opened 2019-09-20 04:24 UTC
Extension broke with new 3.34 update

**Comment by kouros17** [comment] 2019-09-23 07:31
The same here in manjaro. Please fix it.

**Comment by corecoding** [comment] 2019-09-23 14:08
I’m looking into it. Please know that this extension is not marked with 3.34 compatibility. Also, I’m accepting pull requests if anyone can help expedite the process.

**Comment by corecoding** [comment] 2019-09-23 14:29
Duplicate of #103

**Closed by corecoding** 2019-09-23 14:29 UTC
