### ISSUE TITLE
Network aggregate stats should ignore localhost (lo) traffic

### ISSUE THREAD

**Issue by wmertens** [corecoding/Vitals#226] opened 2022-01-24 07:16 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### Describe the new feature you would like

While it is interesting to see localhost traffic in the expanded menu (applications talking to themselves etc), it doesn't matter for max throughput.

Aggregate stats like max or sum should not include the `lo` interface, since for those you're only interested in interaction between outside world and your computer.

**Comment by corecoding** [comment] 2022-01-31 13:35
Thank you for this request, It is a duplicate of #217. Please see that issue for progress updates.

**Closed by corecoding** 2022-01-31 13:35 UTC
Labels: feature
