### ISSUE TITLE
Vitals crashing

### ISSUE THREAD

**Issue by heynnema** [corecoding/Vitals#171] opened 2020-10-21 23:33 UTC
Ubuntu 20.04.1

Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: Object .Gjs_Vitals_CoreCoding_com_menuItem_MenuItem (0x5624b4ce3670), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: clutter_actor_destroy: assertion 'CLUTTER_IS_ACTOR (self)' failed
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: == Stack trace for context 0x56239de4d720 ==
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #0   5624c9987778 i   /home/alheynneman/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/extension.js:507 (3ce4c90678f8 @ 90)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #1   7ffd438e9060 b   resource:///org/gnome/gjs/modules/script/_legacy.js:82 (2a29bd3a9970 @ 69)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #2   5624c99876f0 i   /home/alheynneman/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/extension.js:535 (3b4a059be4c0 @ 12)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #3   5624c9987618 i   resource:///org/gnome/shell/ui/extensionSystem.js:108 (3b4a05964628 @ 394)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #4   5624c9987588 i   resource:///org/gnome/shell/ui/extensionSystem.js:624 (3b4a0596a8f8 @ 15)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #5   7ffd438ea060 b   self-hosted:266 (2a29bd3ace20 @ 259)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #6   5624c99874f8 i   resource:///org/gnome/shell/ui/extensionSystem.js:623 (3b4a0596a880 @ 98)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #7   5624c9987468 i   resource:///org/gnome/shell/ui/extensionSystem.js:641 (3b4a0596a970 @ 82)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #8   7ffd438eaf20 b   self-hosted:1009 (3ce4c90a2268 @ 423)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #9   7ffd438eb020 b   resource:///org/gnome/gjs/modules/core/_signals.js:133 (2a29bd3ac880 @ 427)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #10   7ffd438ebd00 b   resource:///org/gnome/shell/ui/sessionMode.js:198 (3ce4c9025880 @ 286)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #11   5624c9987208 i   resource:///org/gnome/shell/ui/sessionMode.js:159 (3ce4c90256a0 @ 40)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #12   5624c9987150 i   resource:///org/gnome/shell/ui/screenShield.js:574 (3ce4c9013880 @ 191)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #13   5624c99870b8 i   resource:///org/gnome/shell/ui/screenShield.js:311 (3ce4c900ed30 @ 36)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #14   7ffd438ec9e0 b   self-hosted:1011 (3ce4c90a2268 @ 454)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #15   5624c9987028 i   resource:///org/gnome/shell/ui/lightbox.js:195 (3b4a05933d30 @ 29)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #16   5624c9986f98 i   resource:///org/gnome/shell/ui/environment.js:75 (2a29bd38d5b0 @ 98)
Oct 21 09:29:16 Satellite-E55 gnome-shell[4478]: #17   5624c9986f08 i   resource:///org/gnome/shell/ui/environment.js:149 (2a29bd38d9e8 @ 14)

**Comment by corecoding** [comment] 2020-12-11 07:05
Closing due to duplicate of #177

**Closed by corecoding** 2020-12-11 07:05 UTC
