### ISSUE TITLE
[Bug] "CPU Package id 0" sensor sometimes switches to "asus temp1" in the panel after reboot

### ISSUE THREAD

**Issue by hyuri** [corecoding/Vitals#248] opened 2022-04-10 15:08 UTC
### Has this issue been covered in the Wiki?

- [X] I have read the Wiki and my issue is not covered.

### Is there an existing issue reported already?

- [X] I have searched the existing issues, it does not exist.

### What is the unexpected behavior?

I have selected "CPU Package id 0" (temperature average of CPU cores, as I understand it) to be displayed in the panel. However, sometimes, when I power up or reboot, the temperature displayed in the panel is now "asus temp1" -- which, by the way, is always displayed at around a ridiculous 6280°C.

So I have to keep switching back to "CPU Package id 0" almost every time I reboot.

### Steps to reproduce the unexpected behavior.

1. Click on Vitals panel entry;
2. Click to select "CPU Package id 0";
3. Reboot, hard reboot, or power off/on;
4. See error.

### What distribution and version of Linux are you using?

Pop!_OS 21.10

### What version of Gnome are you using?

40

**Comment by corecoding** [comment] 2022-04-10 23:37
This is a duplicate of #245. Two people have tried the develop version and confirmed it is fixed. If you can hop on that thread and give it a try I'd appreciate it.

**Closed** 2022-04-10 23:37 UTC
Labels: bug
