### ISSUE TITLE
Vitals increases status bar padding of other elements

### ISSUE THREAD

**Issue by terencode** [corecoding/Vitals#141] opened 2020-05-02 17:33 UTC
**To Reproduce**
1. Enable the extension
2. Notice the padding of the different element of gnome-shell status bar is increased

**Expected behavior**
The padding of the other status bar elements like the one from the appindicator extension on the left and the gnome-shell owns icons on the right should stay the same.

**Video**
![screencast](https://user-images.githubusercontent.com/12665563/80871172-75179f00-8cab-11ea-8340-ca3994793ed7.gif)

**Desktop**
 - OS: ArchLinux 5.6.10
 - Gnome Version 3.36

**Comment by corecoding** [comment] 2020-05-03 22:10
This sounds like a duplicate of #136. Can you help me by disabling all your extensions, and with Vitals on, see which extension combined with Vitals makes this happen?

**Comment by terencode** [comment] 2020-05-03 22:14
It happens with all extensions disabled except Vitals.

**Comment by corecoding** [comment] 2020-05-04 07:31
That makes it more difficult to fix - like taking your car to the mechanic. They would need to hear the "noise". Can anyone else shed some light on how to duplicate this?

**Comment by corecoding** [comment] 2020-05-05 03:36
Just thought of something @terencode  - did you override any of your system fonts?

**Comment by terencode** [comment] 2020-05-05 16:54
I think so, here are my settings:
![image](https://user-images.githubusercontent.com/12665563/81092973-b3a69700-8f01-11ea-87b3-43357a892e83.png)

I tried to revert the scaling factor to 1 but I could still reproduce the issue, it's just less noticeable.

**Comment by corecoding** [comment] 2020-05-06 03:57
Can you do me a huge favor? Inside .local/share/gnome-shell/extensions/Vitals@CoreCoding.com/stylesheet.css there are a few CSS entries. Can you edit the file, remove one line at a time, save the file, and restart gnome? alt-f2 then type 'r' . Turning the extension on and off in the Extensions app may not reload the stylesheet. I am curious if one of these css statements is bleeding over.

**Comment by terencode** [comment] 2020-05-06 08:09
You are the one doing me a huge favor with trying to figure this out :)

The culprit is `#panel .panel-button .system-status-icon { margin: 0 4px 0 8px; padding: 0; }` !
Removing it and restarting gnome-shell makes everything looks normal again.

**Comment by vesterlay** [comment] 2020-05-07 01:02
I've the same issue on my end. No settings have been changed, manjaro gnome. 
![bug](https://user-images.githubusercontent.com/39202451/81243052-04f07c80-900f-11ea-9b86-4b027563dc5d.png)

**Comment by corecoding** [comment] 2020-05-07 02:55
@terencode @vesterlay can you two check out the develop branch and see if it is fixed?

**Comment by vesterlay** [comment] 2020-05-07 03:34
It's alright now.

**Comment by corecoding** [comment] 2020-05-07 03:43
I added some padding between the icon/text bundles in the panel. What do you think?

**Comment by terencode** [comment] 2020-05-07 09:16
Nice but now I have an extra icon that does not show any value (ellipsized):
![image](https://user-images.githubusercontent.com/12665563/81276957-03957300-9054-11ea-9b21-04de079b39d6.png)

Also would it be possible to force vitals to be the first when put to the right? 
Right now here is how it looks: 
![image](https://user-images.githubusercontent.com/12665563/81277082-30e22100-9054-11ea-8cc9-382b5cec6f10.png)

I would like it to be on the very left, before the screenshot and clipboard manager extension.

**Comment by corecoding** [comment] 2020-05-09 14:38
That will be another feature request. :) Not sure if it can be done, but I want to focus on the bugs right now. Closing this ticket. Woohoo

**Closed by corecoding** 2020-05-09 14:38 UTC
Labels: bug

**Comment by terencode** [comment] 2020-05-09 17:46
I had a quick look and it doesn't seem possible, Vitals already tries to be the first when set to the right panel... 
What would be needed is an extension or a native way to reorder those icons...
